[package]
name = "era"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", default-features = false, features = ["bevy_state"] }
bevy_ratatui = "0.10.0"
chrono = "0.4.42"
crossterm = "0.29.0"
rand = "0.9.2"
